[package]
name = "nanorand-bench"
version = "0.1.0"
authors = ["aspen <aspenuwu@protonmail.com>"]
edition = "2018"

[dependencies]
criterion = "0.3"
fastrand = "^1.4"
hex = "^0.4"
nanorand = { path = "../nanorand" }
oorandom = "^11.1"
rand_chacha = "^0.3"
rand_core = "^0.5"
rand_pcg = "^0.2"
random-fast-rng = "^0.1"
randomize = "^3.0"
wyhash = "^0.4"

[[bench]]
name = "speed"
harness = false
