[package]
name = "nanorand-py"
description = "A Python module for nanorand"
repository = "https://github.com/aspenluxxxy/nanorand-rs"
version = "0.5.0"
authors = ["aspen <luxx4x@protonmail.com>"]
edition = "2018"
license = "Zlib"
publish = false

[lib]
name = "pynanorand"
crate-type = ["cdylib"]

[dependencies.nanorand]
path = "../nanorand"
default-features = false
features = ["std", "wyrand", "pcg64", "chacha", "getrandom"]

[dependencies.pyo3]
version = "0.12"
features = ["extension-module"]
